const express = require("express")
const router = express.Router()
const { createData } = require("../controllers/CreateData")
const { register } = require("../controllers/Register")
const { Login } = require("../controllers/Login")
const { sendOTP } = require("../controllers/sendOTP")
const { verifyOTP } = require("../controllers/verifyOTP")
const { changePassword } = require("../controllers/ChangePassword")
const { getInfoUser } = require("../controllers/getInfoUser")
const { editPassword } = require("../controllers/EditPassword")
const { getSemesterList } = require("../controllers/GetSemesterList")
const { getData } = require("../controllers/getData")
const { getDetailData } = require("../controllers/getDetailData")
const { getUserSchedule } = require("../controllers/getUserSchedule")
const { getLichthiByMSSV } = require("../controllers/getLichthiByMSSV")
const { getCurriculum } = require("../controllers/GetCurriculum")
const { getRequired } = require("../controllers/getRequired")
const { getMajor_id } = require("../controllers/getMajor_id")
const { getStudyProgress } = require("../controllers/getStudyProgress")
const { getStudentInfo } = require("../controllers/getStudentInfo")

router.get("/", (req, res) => res.send("hello khac kien !"))
router.get("/createData", createData)
router.post("/register", register)
router.post("/login", Login)
router.post("/sendOTP", sendOTP)
router.post("/verify", verifyOTP)
router.put("/changePassword", changePassword)
router.put("/editPassword", editPassword)
router.get("/semesterList", getSemesterList)
router.get("/getInfo", getInfoUser)
router.get("/getData", getData)
router.get("/getDetailData", getDetailData)
router.get("/getUserSchedule", getUserSchedule)
router.get("/getLichthiByMSSV", getLichthiByMSSV)
router.get("/getCurriculum", getCurriculum)
router.get("/getRequired", getRequired)
router.get("/getMajor_id", getMajor_id)
router.get("/getStudyProgress", getStudyProgress)
router.get("/getStudentInfo", getStudentInfo)
module.exports = router
